services:
  - type: web
    name: osint-spectre
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: SHODAN_API_KEY
        sync: false
      - key: HUNTER_API_KEY
        sync: false
      - key: DEHASHED_EMAIL
        sync: false
      - key: DEHASHED_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: SNUSBASE_API_KEY
        sync: false
      - key: BETA_SNUSBASE_KEY
        sync: false
      - key: LEAKCHECK_API_KEY
        sync: false
      - key: INTELVAULT_KEY
        sync: false
      - key: CSINT_TOOLS_KEY1
        sync: false
      - key: CSINT_TOOLS_KEY2
        sync: false
      - key: TRACKED_SH_KEY1
        sync: false
      - key: TRACKED_SH_KEY2
        sync: false
      - key: OSINTCAT_KEY1
        sync: false
      - key: OSINTCAT_KEY2
        sync: false
      - key: SOURCE_RED_KEY
        sync: false
      - key: SEON_API_KEY
        sync: false
      - key: OSINTWAVE_KEY
        sync: false
      - key: GOLOOKUP_EMAIL
        sync: false
      - key: GOLOOKUP_PASS
        sync: false
